services:
    app_user.registration_complet:
        class: ProjectBundle\EventListener\RegistrationConfirmListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }

